services:
  - type: web
    name: melee-tournament-app
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
