SUPABASE_URL = "https://zxlumrmkuuighyfxzshg.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4bHVtcm1rdXVpZ2h5Znh6c2hnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NzM1NjYsImV4cCI6MjA2MjU0OTU2Nn0.e_T9zfCv8lUjSQEAYTKnjN8w2KDCe-QpIuzTSPBRRxk"
